# Form implementation generated from reading ui file 'client/game_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 850)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #0a0b0a;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #1a1d1a, stop:1 #050505);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #3a413a;\n"
"    border-radius: 4px;\n"
"    margin-top: 20px;\n"
"    background-color: rgba(20, 25, 20, 220);\n"
"    color: #c5a059;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI Semibold\";\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #252a25;\n"
"    border: 1px solid #454d45;\n"
"    color: #e0e0e0;\n"
"    border-radius: 3px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353d35;\n"
"    border: 1px solid #c5a059;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #151815;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"QLabel#resultLabel {\n"
"    background-color: #0f120f;\n"
"    border: 1px solid #2a302a;\n"
"    padding: 10px;\n"
"    color: #8da38d;\n"
"    font-family: \"Consolas\";\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.headerFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.headerFrame.setObjectName("headerFrame")
        self.headerContent = QtWidgets.QVBoxLayout(self.headerFrame)
        self.headerContent.setObjectName("headerContent")
        self.titleLabel = QtWidgets.QLabel(parent=self.headerFrame)
        self.titleLabel.setStyleSheet("font-size: 32px; font-weight: bold; color: #c5a059; letter-spacing: 10px;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.headerContent.addWidget(self.titleLabel)
        self.playerInfoLabel = QtWidgets.QLabel(parent=self.headerFrame)
        self.playerInfoLabel.setStyleSheet("font-size: 14px; color: #ff4444; font-style: italic;")
        self.playerInfoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.playerInfoLabel.setObjectName("playerInfoLabel")
        self.headerContent.addWidget(self.playerInfoLabel)
        self.mainLayout.addWidget(self.headerFrame)
        self.gameAreaLayout = QtWidgets.QHBoxLayout()
        self.gameAreaLayout.setObjectName("gameAreaLayout")
        self.statusGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.statusGroupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.statusGroupBox.setObjectName("statusGroupBox")
        self.statusLayout = QtWidgets.QVBoxLayout(self.statusGroupBox)
        self.statusLayout.setObjectName("statusLayout")
        self.currentPlayerLabel = QtWidgets.QLabel(parent=self.statusGroupBox)
        self.currentPlayerLabel.setObjectName("currentPlayerLabel")
        self.statusLayout.addWidget(self.currentPlayerLabel)
        self.phaseLabel = QtWidgets.QLabel(parent=self.statusGroupBox)
        self.phaseLabel.setObjectName("phaseLabel")
        self.statusLayout.addWidget(self.phaseLabel)
        self.reinforcementLabel = QtWidgets.QLabel(parent=self.statusGroupBox)
        self.reinforcementLabel.setStyleSheet("color: #00ff00;")
        self.reinforcementLabel.setObjectName("reinforcementLabel")
        self.statusLayout.addWidget(self.reinforcementLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.statusLayout.addItem(spacerItem)
        self.legendFrame = QtWidgets.QFrame(parent=self.statusGroupBox)
        self.legendFrame.setObjectName("legendFrame")
        self.legendLayout = QtWidgets.QVBoxLayout(self.legendFrame)
        self.legendLayout.setObjectName("legendLayout")
        self.p1LegendLabel = QtWidgets.QLabel(parent=self.legendFrame)
        self.p1LegendLabel.setStyleSheet("color: #ff4444;")
        self.p1LegendLabel.setObjectName("p1LegendLabel")
        self.legendLayout.addWidget(self.p1LegendLabel)
        self.p2LegendLabel = QtWidgets.QLabel(parent=self.legendFrame)
        self.p2LegendLabel.setStyleSheet("color: #4444ff;")
        self.p2LegendLabel.setObjectName("p2LegendLabel")
        self.legendLayout.addWidget(self.p2LegendLabel)
        self.statusLayout.addWidget(self.legendFrame)
        self.gameAreaLayout.addWidget(self.statusGroupBox)
        self.mapFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mapFrame.setMinimumSize(QtCore.QSize(700, 500))
        self.mapFrame.setStyleSheet("\n"
"QFrame#mapFrame {\n"
"    background-color: #1b241b;\n"
"    border: 2px solid #c5a059;\n"
"}\n"
"         ")
        self.mapFrame.setObjectName("mapFrame")
        self.trakyaButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.trakyaButton.setGeometry(QtCore.QRect(360, 180, 70, 55))
        self.trakyaButton.setStyleSheet("background-color: rgba(139, 0, 0, 180); border: 2px solid #ff4444; color: white; border-radius: 15px;")
        self.trakyaButton.setObjectName("trakyaButton")
        self.anadoluButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.anadoluButton.setGeometry(QtCore.QRect(430, 230, 80, 60))
        self.anadoluButton.setStyleSheet("background-color: rgba(139, 0, 0, 180); border: 2px solid #ff4444; color: white; border-radius: 15px;")
        self.anadoluButton.setObjectName("anadoluButton")
        self.kafkasyaButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.kafkasyaButton.setGeometry(QtCore.QRect(540, 180, 90, 55))
        self.kafkasyaButton.setStyleSheet("background-color: rgba(0, 50, 139, 180); border: 2px solid #4444ff; color: white; border-radius: 15px;")
        self.kafkasyaButton.setObjectName("kafkasyaButton")
        self.balkanlarButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.balkanlarButton.setGeometry(QtCore.QRect(300, 250, 90, 55))
        self.balkanlarButton.setStyleSheet("background-color: rgba(0, 50, 139, 180); border: 2px solid #4444ff; color: white; border-radius: 15px;")
        self.balkanlarButton.setObjectName("balkanlarButton")
        self.ortaDoguButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.ortaDoguButton.setGeometry(QtCore.QRect(500, 330, 95, 55))
        self.ortaDoguButton.setStyleSheet("background-color: rgba(139, 0, 0, 180); border: 2px solid #ff4444; color: white; border-radius: 15px;")
        self.ortaDoguButton.setObjectName("ortaDoguButton")
        self.kuzeyAfrikaButton = QtWidgets.QPushButton(parent=self.mapFrame)
        self.kuzeyAfrikaButton.setGeometry(QtCore.QRect(310, 390, 120, 55))
        self.kuzeyAfrikaButton.setStyleSheet("background-color: rgba(0, 50, 139, 180); border: 2px solid #4444ff; color: white; border-radius: 15px;")
        self.kuzeyAfrikaButton.setObjectName("kuzeyAfrikaButton")
        self.gameAreaLayout.addWidget(self.mapFrame)
        self.attackGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.attackGroupBox.setMinimumSize(QtCore.QSize(220, 0))
        self.attackGroupBox.setObjectName("attackGroupBox")
        self.attackLayout = QtWidgets.QVBoxLayout(self.attackGroupBox)
        self.attackLayout.setObjectName("attackLayout")
        self.attackerLabel = QtWidgets.QLabel(parent=self.attackGroupBox)
        self.attackerLabel.setObjectName("attackerLabel")
        self.attackLayout.addWidget(self.attackerLabel)
        self.defenderLabel = QtWidgets.QLabel(parent=self.attackGroupBox)
        self.defenderLabel.setObjectName("defenderLabel")
        self.attackLayout.addWidget(self.defenderLabel)
        self.territoryList = QtWidgets.QListWidget(parent=self.attackGroupBox)
        self.territoryList.setStyleSheet("background: transparent; border: 1px solid #333; color: #e0e0e0;")
        self.territoryList.setObjectName("territoryList")
        self.attackLayout.addWidget(self.territoryList)
        self.diceFrame = QtWidgets.QFrame(parent=self.attackGroupBox)
        self.diceFrame.setMinimumSize(QtCore.QSize(0, 60))
        self.diceFrame.setStyleSheet("background-color: #111511; border: 1px solid #2a302a;")
        self.diceFrame.setObjectName("diceFrame")
        self.attackLayout.addWidget(self.diceFrame)
        self.gameAreaLayout.addWidget(self.attackGroupBox)
        self.mainLayout.addLayout(self.gameAreaLayout)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.resultLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.resultLabel.setObjectName("resultLabel")
        self.bottomLayout.addWidget(self.resultLabel)
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.attackButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.attackButton.setMinimumSize(QtCore.QSize(180, 45))
        self.attackButton.setStyleSheet("background-color: #631212; border: 1px solid #ff4444;")
        self.attackButton.setObjectName("attackButton")
        self.buttonLayout.addWidget(self.attackButton)
        self.nextTurnButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nextTurnButton.setMinimumSize(QtCore.QSize(180, 45))
        self.nextTurnButton.setStyleSheet("background-color: #124012; border: 1px solid #44ff44;")
        self.nextTurnButton.setObjectName("nextTurnButton")
        self.buttonLayout.addWidget(self.nextTurnButton)
        self.bottomLayout.addLayout(self.buttonLayout)
        self.mainLayout.addLayout(self.bottomLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RISK: Global Tactics"))
        self.titleLabel.setText(_translate("MainWindow", "RISK GAME"))
        self.playerInfoLabel.setText(_translate("MainWindow", "Commander: Player Info"))
        self.statusGroupBox.setTitle(_translate("MainWindow", "TACTICAL STATUS"))
        self.currentPlayerLabel.setText(_translate("MainWindow", "Current: Player 1"))
        self.phaseLabel.setText(_translate("MainWindow", "Phase: ATTACK"))
        self.reinforcementLabel.setText(_translate("MainWindow", "Reinforcements: +4"))
        self.p1LegendLabel.setText(_translate("MainWindow", "● P1: Red Division"))
        self.p2LegendLabel.setText(_translate("MainWindow", "● P2: Blue Division"))
        self.trakyaButton.setText(_translate("MainWindow", "Trakya\n"
"3"))
        self.anadoluButton.setText(_translate("MainWindow", "Anadolu\n"
"12"))
        self.kafkasyaButton.setText(_translate("MainWindow", "Kafkasya\n"
"5"))
        self.balkanlarButton.setText(_translate("MainWindow", "Balkanlar\n"
"4"))
        self.ortaDoguButton.setText(_translate("MainWindow", "Orta Dogu\n"
"7"))
        self.kuzeyAfrikaButton.setText(_translate("MainWindow", "Kuzey Afrika\n"
"6"))
        self.attackGroupBox.setTitle(_translate("MainWindow", "COMMAND CENTER"))
        self.attackerLabel.setText(_translate("MainWindow", "FROM: None"))
        self.defenderLabel.setText(_translate("MainWindow", "TARGET: None"))
        self.resultLabel.setText(_translate("MainWindow", "[SYSTEM]: Waiting for action..."))
        self.attackButton.setText(_translate("MainWindow", "SALDIR"))
        self.nextTurnButton.setText(_translate("MainWindow", "TURU BİTİR"))
