# Form implementation generated from reading ui file 'client\waiting_window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 100, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(25)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.playerInfoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.playerInfoLabel.setGeometry(QtCore.QRect(60, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.playerInfoLabel.setFont(font)
        self.playerInfoLabel.setObjectName("playerInfoLabel")
        self.player_info_layer = QtWidgets.QLabel(parent=self.centralwidget)
        self.player_info_layer.setGeometry(QtCore.QRect(250, 220, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.player_info_layer.setFont(font)
        self.player_info_layer.setText("")
        self.player_info_layer.setObjectName("player_info_layer")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("client\\../assets/waiting_room_background.jpg"))
        self.label_3.setObjectName("label_3")
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(220, 480, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.label_3.raise_()
        self.label.raise_()
        self.playerInfoLabel.raise_()
        self.player_info_layer.raise_()
        self.statusLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RİSK OYUNU"))
        self.playerInfoLabel.setText(_translate("MainWindow", "OYUNCU:"))
        self.statusLabel.setText(_translate("MainWindow", "Rakip oyuncunun bağlanması bekleniyor..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
